import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

/**
 * VABIX platform IAM tables. Namespaced so they never collide with MyBizCar
 * tables on prod:accomplished-rabbit-409 (especially `users`).
 *
 * NEVER add a table named `users` (or other MyBizCar names) in this file.
 * Deploying this schema alone to that deployment would drop undeclared tables.
 * Merge these `platform*` tables into the existing Convex project first.
 * See convex/README.md and docs/PLATFORM_CONVEX.md.
 */
export default defineSchema({
  platformUsers: defineTable({
    platformId: v.string(),
    email: v.string(),
    emailLower: v.string(),
    name: v.string(),
    passwordHash: v.union(v.string(), v.null()),
    avatarFileId: v.union(v.string(), v.null()),
    role: v.union(v.literal("admin"), v.literal("mod"), v.literal("user")),
    departmentId: v.union(v.string(), v.null()),
    status: v.union(
      v.literal("pending"),
      v.literal("active"),
      v.literal("locked"),
      v.literal("archived"),
    ),
    lastLoginAt: v.union(v.string(), v.null()),
    createdAt: v.string(),
    updatedAt: v.string(),
    createdBy: v.union(v.string(), v.null()),
    updatedBy: v.union(v.string(), v.null()),
    archivedAt: v.union(v.string(), v.null()),
    isSeed: v.boolean(),
  })
    .index("by_platformId", ["platformId"])
    .index("by_emailLower", ["emailLower"])
    .index("by_role_status", ["role", "status"])
    .index("by_departmentId", ["departmentId"]),

  platformAuthSessions: defineTable({
    platformId: v.string(),
    userId: v.string(),
    expiresAt: v.string(),
    revokedAt: v.union(v.string(), v.null()),
    userAgent: v.union(v.string(), v.null()),
    createdAt: v.string(),
  })
    .index("by_platformId", ["platformId"])
    .index("by_userId", ["userId"]),

  platformAuthTokens: defineTable({
    platformId: v.string(),
    userId: v.string(),
    purpose: v.union(v.literal("activation"), v.literal("reset")),
    tokenHash: v.string(),
    expiresAt: v.string(),
    usedAt: v.union(v.string(), v.null()),
    createdAt: v.string(),
    createdBy: v.union(v.string(), v.null()),
  })
    .index("by_platformId", ["platformId"])
    .index("by_tokenHash", ["tokenHash"])
    .index("by_userId", ["userId"]),

  platformPermissionGroups: defineTable({
    platformId: v.string(),
    code: v.string(),
    name: v.string(),
    description: v.string(),
    status: v.union(v.literal("active"), v.literal("archived")),
    isSeed: v.boolean(),
    createdAt: v.string(),
    updatedAt: v.string(),
    createdBy: v.union(v.string(), v.null()),
    updatedBy: v.union(v.string(), v.null()),
    archivedAt: v.union(v.string(), v.null()),
  })
    .index("by_platformId", ["platformId"])
    .index("by_code", ["code"]),

  platformPermissionGroupMembers: defineTable({
    groupId: v.string(),
    userId: v.string(),
    createdAt: v.string(),
    createdBy: v.union(v.string(), v.null()),
  })
    .index("by_userId", ["userId"])
    .index("by_groupId", ["groupId"])
    .index("by_group_user", ["groupId", "userId"]),

  platformPermissionGroupGrants: defineTable({
    platformId: v.string(),
    groupId: v.string(),
    menuCode: v.string(),
    action: v.string(),
    scope: v.string(),
  })
    .index("by_platformId", ["platformId"])
    .index("by_groupId", ["groupId"])
    .index("by_group_menu_action", ["groupId", "menuCode", "action"]),

  platformAuditLogs: defineTable({
    platformId: v.string(),
    actorUserId: v.union(v.string(), v.null()),
    action: v.string(),
    entityType: v.string(),
    entityId: v.union(v.string(), v.null()),
    summary: v.string(),
    metadata: v.string(),
    ip: v.union(v.string(), v.null()),
    createdAt: v.string(),
  })
    .index("by_platformId", ["platformId"])
    .index("by_createdAt", ["createdAt"])
    .index("by_entity", ["entityType", "entityId"]),

/** Auto-merged MyBizCar tables — keep so deploy does not drop existing cloud data. */
  activationAssessments: defineTable({
    assessedAt: v.union(v.string(), v.null()),
    assessmentId: v.string(),
    componentCode: v.string(),
    evidenceReferences: v.string(),
    id: v.string(),
    rationale: v.string(),
    scope: v.string(),
    score: v.union(v.number(), v.null()),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_business_id", ["id"]),
  assessmentContexts: defineTable({
    assessmentId: v.string(),
    businessUnit: v.string(),
    companySize: v.string(),
    companyStage: v.string(),
    id: v.string(),
    industry: v.string(),
    notes: v.string(),
    scope: v.string(),
    timeHorizon: v.string(),
    updatedAt: v.string(),
  }).index("by_business_id", ["id"]),
  assessmentSnapshots: defineTable({
    id: v.string(),
  }).index("by_business_id", ["id"]),
  assessments: defineTable({
    assessmentDate: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
    id: v.string(),
    isDemo: v.boolean(),
    lockedAt: v.union(v.string(), v.null()),
    lockedBy: v.union(v.string(), v.null()),
    nextReviewDate: v.string(),
    organizationId: v.string(),
    parentAssessmentId: v.union(v.string(), v.null()),
    primaryEvaluatorId: v.string(),
    revisionNumber: v.number(),
    secondaryEvaluatorId: v.union(v.string(), v.null()),
    standardVersionId: v.string(),
    status: v.string(),
    title: v.string(),
    updatedAt: v.string(),
  }).index("by_business_id", ["id"]),
  auditLogs: defineTable({
    action: v.string(),
    actorUserId: v.string(),
    assessmentId: v.string(),
    createdAt: v.string(),
    entityId: v.string(),
    entityType: v.string(),
    id: v.string(),
    ip: v.union(v.string(), v.null()),
    newValue: v.string(),
    oldValue: v.union(v.string(), v.null()),
    organizationId: v.string(),
    reason: v.string(),
    standardVersionId: v.string(),
  }).index("by_business_id", ["id"]),
  cfsConnectionScores: defineTable({
    assessmentId: v.string(),
    connectionCode: v.string(),
    deviationSignal: v.string(),
    evaluatorNote: v.string(),
    evidence: v.string(),
    evidenceStatus: v.string(),
    id: v.string(),
    score: v.union(v.number(), v.null()),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_business_id", ["id"]),
  comments: defineTable({
    assessmentId: v.string(),
    body: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
    id: v.string(),
  }).index("by_business_id", ["id"]),
  componentAssessments: defineTable({
    assessmentId: v.string(),
    componentCode: v.string(),
    evidenceGrade: v.union(v.string(), v.null()),
    id: v.string(),
    narrative: v.string(),
    requiredLevel: v.number(),
    updatedAt: v.string(),
  }).index("by_business_id", ["id"]),
  criterionAnchors: defineTable({
    criterionId: v.string(),
    descriptionVi: v.string(),
    id: v.string(),
    score: v.number(),
  }).index("by_business_id", ["id"]),
  criterionScores: defineTable({
    assessmentId: v.string(),
    calibrationStatus: v.string(),
    criterionCode: v.string(),
    criterionId: v.string(),
    evaluatorExplanation: v.string(),
    evidenceNote: v.string(),
    evidenceReferences: v.string(),
    id: v.string(),
    primaryScore: v.union(v.number(), v.null()),
    secondaryScore: v.union(v.string(), v.null()),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_business_id", ["id"]),
  evidenceItems: defineTable({
    assessmentId: v.string(),
    componentCode: v.string(),
    connectionCode: v.union(v.string(), v.null()),
    createdAt: v.string(),
    createdBy: v.string(),
    criterionCode: v.string(),
    fileName: v.union(v.string(), v.null()),
    fileSize: v.union(v.string(), v.null()),
    id: v.string(),
    kind: v.string(),
    linkUrl: v.union(v.string(), v.null()),
    mimeType: v.union(v.string(), v.null()),
    note: v.string(),
    storageKey: v.union(v.string(), v.null()),
    title: v.string(),
  }).index("by_business_id", ["id"]),
  forceAssessments: defineTable({
    assessmentId: v.string(),
    bottleneckProximity: v.union(v.number(), v.null()),
    componentCode: v.string(),
    direction: v.union(v.string(), v.null()),
    duration: v.union(v.number(), v.null()),
    evidenceGrade: v.union(v.string(), v.null()),
    evidenceNote: v.string(),
    id: v.string(),
    intensity: v.union(v.number(), v.null()),
    scope: v.union(v.number(), v.null()),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_business_id", ["id"]),
  improvementActions: defineTable({
    assessmentId: v.string(),
    causeHypothesis: v.string(),
    componentCode: v.string(),
    connectionNote: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
    evidence: v.string(),
    experimentId: v.string(),
    id: v.string(),
    mechanism: v.string(),
    ownerName: v.string(),
    ownerUserId: v.string(),
    priorityReason: v.string(),
    priorityScore: v.number(),
    reviewDate: v.string(),
    scope: v.string(),
    sideEffect: v.string(),
    stage: v.string(),
    symptom: v.string(),
    testPeriod: v.string(),
    title: v.string(),
    updatedAt: v.string(),
  }).index("by_business_id", ["id"]),
  improvementExperiments: defineTable({
    assessmentId: v.string(),
    baselineLockedAt: v.union(v.string(), v.null()),
    compareAssessmentId: v.union(v.string(), v.null()),
    createdAt: v.string(),
    createdBy: v.string(),
    decision: v.union(v.string(), v.null()),
    decisionNote: v.string(),
    id: v.string(),
    startDate: v.string(),
    title: v.string(),
    updatedAt: v.string(),
  }).index("by_business_id", ["id"]),
  leads: defineTable({
    id: v.string(),
  }).index("by_business_id", ["id"]),
  organizationMembers: defineTable({
    createdAt: v.string(),
    createdBy: v.string(),
    id: v.string(),
    organizationId: v.string(),
    role: v.string(),
    userId: v.string(),
  }).index("by_business_id", ["id"]),
  organizations: defineTable({
    confidentialityNote: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
    id: v.string(),
    industry: v.string(),
    isDemo: v.boolean(),
    name: v.string(),
    size: v.string(),
    slug: v.string(),
    stage: v.string(),
    updatedAt: v.string(),
  }).index("by_business_id", ["id"]),
  revokedSessions: defineTable({
    id: v.string(),
    jti: v.string(),
    revokedAt: v.string(),
    userId: v.string(),
  }).index("by_business_id", ["id"]),
  sharePermissions: defineTable({
    assessmentId: v.string(),
    canEdit: v.boolean(),
    createdAt: v.string(),
    createdBy: v.string(),
    id: v.string(),
    userId: v.string(),
  }).index("by_business_id", ["id"]),
  standardCfsConnections: defineTable({
    code: v.string(),
    critical: v.boolean(),
    from: v.string(),
    id: v.string(),
    nameVi: v.string(),
    standardVersionId: v.string(),
    to: v.string(),
    weight: v.number(),
    weightAssumptionNote: v.string(),
  }).index("by_business_id", ["id"]),
  standardComponents: defineTable({
    code: v.string(),
    id: v.string(),
    mnemonic: v.string(),
    mnemonicMeaning: v.string(),
    nameEn: v.string(),
    nameVi: v.string(),
    requiredLevelDefault: v.number(),
    sortOrder: v.number(),
    standardVersionId: v.string(),
  }).index("by_business_id", ["id"]),
  standardCriteria: defineTable({
    code: v.string(),
    componentCode: v.string(),
    critical: v.boolean(),
    id: v.string(),
    nameVi: v.string(),
    sortOrder: v.number(),
    standardVersionId: v.string(),
    weight: v.number(),
  }).index("by_business_id", ["id"]),
  standardThresholds: defineTable({
    activationFormulaNote: v.string(),
    calibrationScoreDelta: v.number(),
    cfsCriticalCap: v.number(),
    cfsCriticalConnectionFloor: v.number(),
    cfsFormulaNote: v.string(),
    criticalScoreCap2: v.number(),
    criticalScoreCap4: v.number(),
    evidenceCapC: v.number(),
    evidenceCapD: v.number(),
    id: v.string(),
    standardVersionId: v.string(),
    visualMappingNote: v.string(),
  }).index("by_business_id", ["id"]),
  standardVersions: defineTable({
    approvalNote: v.string(),
    changeReason: v.string(),
    code: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
    developmentDisclaimer: v.string(),
    effectiveDate: v.string(),
    id: v.string(),
    impactNote: v.string(),
    name: v.string(),
    status: v.string(),
    updatedAt: v.string(),
    version: v.string(),
  }).index("by_business_id", ["id"]),
  users: defineTable({
    createdAt: v.string(),
    email: v.string(),
    id: v.string(),
    isActive: v.boolean(),
    isDemo: v.boolean(),
    name: v.string(),
    passwordHash: v.string(),
    updatedAt: v.string(),
  }).index("by_business_id", ["id"]),
});
