import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const nullableString = v.union(v.string(), v.null());
const nullableNumber = v.union(v.number(), v.null());
const nullableBoolean = v.union(v.boolean(), v.null());

export default defineSchema({
  leads: defineTable({
    type: v.string(),
    name: v.string(),
    company: v.optional(v.string()),
    role: v.optional(v.string()),
    phone: v.string(),
    email: v.string(),
    companySize: v.optional(v.string()),
    need: v.optional(v.string()),
    message: v.optional(v.string()),
    program: v.optional(v.string()),
    eventSlug: v.optional(v.string()),
    source: v.string(),
    createdAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),

  users: defineTable({
    id: v.string(),
    email: v.string(),
    name: v.string(),
    passwordHash: v.string(),
    isDemo: v.boolean(),
    isActive: v.boolean(),
    createdAt: v.string(),
    updatedAt: v.string(),
  })
    .index("by_key", ["id"])
    .index("by_email", ["email"]),

  organizations: defineTable({
    id: v.string(),
    name: v.string(),
    slug: v.string(),
    industry: v.string(),
    stage: v.string(),
    size: v.string(),
    isDemo: v.boolean(),
    confidentialityNote: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
    createdBy: v.string(),
  }).index("by_key", ["id"]),

  organizationMembers: defineTable({
    id: v.string(),
    organizationId: v.string(),
    userId: v.string(),
    role: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
  })
    .index("by_key", ["id"])
    .index("by_user", ["userId"])
    .index("by_org", ["organizationId"]),

  standardVersions: defineTable({
    id: v.string(),
    code: v.string(),
    name: v.string(),
    version: v.string(),
    status: v.string(),
    effectiveDate: v.string(),
    approvalNote: v.string(),
    changeReason: v.string(),
    impactNote: v.string(),
    developmentDisclaimer: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
    createdBy: v.string(),
  }).index("by_key", ["id"]),

  standardComponents: defineTable({
    id: v.string(),
    standardVersionId: v.string(),
    code: v.string(),
    nameEn: v.string(),
    nameVi: v.string(),
    mnemonic: v.string(),
    mnemonicMeaning: v.string(),
    requiredLevelDefault: v.number(),
    sortOrder: v.number(),
  }).index("by_standard", ["standardVersionId"]),

  standardCriteria: defineTable({
    id: v.string(),
    standardVersionId: v.string(),
    componentCode: v.string(),
    code: v.string(),
    nameVi: v.string(),
    weight: v.number(),
    critical: v.boolean(),
    sortOrder: v.number(),
  }).index("by_standard", ["standardVersionId"]),

  criterionAnchors: defineTable({
    id: v.string(),
    criterionId: v.string(),
    score: v.number(),
    descriptionVi: v.string(),
  }).index("by_criterion", ["criterionId"]),

  standardCfsConnections: defineTable({
    id: v.string(),
    standardVersionId: v.string(),
    code: v.string(),
    from: v.string(),
    to: v.string(),
    nameVi: v.string(),
    weight: v.number(),
    critical: v.boolean(),
    weightAssumptionNote: v.string(),
  }).index("by_standard", ["standardVersionId"]),

  standardThresholds: defineTable({
    id: v.string(),
    standardVersionId: v.string(),
    calibrationScoreDelta: v.number(),
    criticalScoreCap2: v.number(),
    criticalScoreCap4: v.number(),
    evidenceCapD: v.number(),
    evidenceCapC: v.number(),
    cfsCriticalConnectionFloor: v.number(),
    cfsCriticalCap: v.number(),
    cfsFormulaNote: v.string(),
    activationFormulaNote: v.string(),
    visualMappingNote: v.string(),
  }).index("by_standard", ["standardVersionId"]),

  assessments: defineTable({
    id: v.string(),
    organizationId: v.string(),
    parentAssessmentId: nullableString,
    revisionNumber: v.number(),
    title: v.string(),
    status: v.string(),
    standardVersionId: v.string(),
    primaryEvaluatorId: v.string(),
    secondaryEvaluatorId: nullableString,
    assessmentDate: v.string(),
    nextReviewDate: nullableString,
    isDemo: v.boolean(),
    lockedAt: nullableString,
    lockedBy: nullableString,
    createdAt: v.string(),
    updatedAt: v.string(),
    createdBy: v.string(),
  })
    .index("by_key", ["id"])
    .index("by_org", ["organizationId"]),

  assessmentContexts: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    businessUnit: v.string(),
    industry: v.string(),
    companyStage: v.string(),
    companySize: v.string(),
    scope: v.string(),
    timeHorizon: v.string(),
    notes: v.string(),
    updatedAt: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  componentAssessments: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    componentCode: v.string(),
    requiredLevel: v.number(),
    evidenceGrade: nullableString,
    narrative: v.string(),
    updatedAt: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  criterionScores: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    criterionId: v.string(),
    criterionCode: v.string(),
    primaryScore: nullableNumber,
    secondaryScore: nullableNumber,
    evidenceNote: v.string(),
    evidenceReferences: v.string(),
    evaluatorExplanation: v.string(),
    calibrationStatus: v.string(),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  activationAssessments: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    componentCode: v.string(),
    score: nullableNumber,
    rationale: v.string(),
    evidenceReferences: v.string(),
    assessedAt: nullableString,
    scope: v.string(),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  forceAssessments: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    componentCode: v.string(),
    direction: nullableString,
    scope: nullableNumber,
    intensity: nullableNumber,
    duration: nullableNumber,
    bottleneckProximity: nullableNumber,
    evidenceGrade: nullableString,
    evidenceNote: v.string(),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  cfsConnectionScores: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    connectionCode: v.string(),
    score: nullableNumber,
    evidence: v.string(),
    evidenceStatus: v.string(),
    deviationSignal: v.string(),
    evaluatorNote: v.string(),
    updatedAt: v.string(),
    updatedBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  evidenceItems: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    componentCode: nullableString,
    criterionCode: nullableString,
    connectionCode: nullableString,
    title: v.string(),
    note: v.string(),
    linkUrl: nullableString,
    storageKey: nullableString,
    mimeType: nullableString,
    fileName: nullableString,
    fileSize: nullableNumber,
    kind: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  assessmentSnapshots: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    kind: v.string(),
    payloadJson: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  improvementExperiments: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    title: v.string(),
    baselineLockedAt: nullableString,
    startDate: nullableString,
    decision: nullableString,
    decisionNote: v.string(),
    compareAssessmentId: nullableString,
    createdAt: v.string(),
    updatedAt: v.string(),
    createdBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  improvementActions: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    experimentId: nullableString,
    stage: v.string(),
    componentCode: nullableString,
    title: v.string(),
    symptom: v.string(),
    causeHypothesis: v.string(),
    connectionNote: v.string(),
    sideEffect: v.string(),
    ownerUserId: nullableString,
    ownerName: v.string(),
    scope: v.string(),
    testPeriod: v.string(),
    mechanism: v.string(),
    evidence: v.string(),
    reviewDate: nullableString,
    priorityScore: v.number(),
    priorityReason: v.string(),
    createdAt: v.string(),
    updatedAt: v.string(),
    createdBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  comments: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    body: v.string(),
    createdAt: v.string(),
    createdBy: v.string(),
  }).index("by_assessment", ["assessmentId"]),

  auditLogs: defineTable({
    id: v.string(),
    actorUserId: v.string(),
    organizationId: nullableString,
    assessmentId: nullableString,
    action: v.string(),
    entityType: v.string(),
    entityId: v.string(),
    oldValue: nullableString,
    newValue: nullableString,
    reason: nullableString,
    standardVersionId: nullableString,
    ip: nullableString,
    createdAt: v.string(),
  }),

  sharePermissions: defineTable({
    id: v.string(),
    assessmentId: v.string(),
    userId: v.string(),
    canEdit: v.boolean(),
    createdAt: v.string(),
    createdBy: v.string(),
  })
    .index("by_assessment", ["assessmentId"])
    .index("by_user", ["userId"]),

  revokedSessions: defineTable({
    id: v.string(),
    jti: v.string(),
    userId: v.string(),
    revokedAt: v.string(),
  }).index("by_jti", ["jti"]),
});
