import type { TrainingProgram } from "./types";

const defaultMethod =
  "Mô thức quản trị → ví dụ thực tế → thực hành trên doanh nghiệp → phản biện đa chiều → cải tiến → cam kết ứng dụng.";

export const programs: TrainingProgram[] = [
  {
    id: "bmdo",
    slug: "bmdo",
    title: "BMDO — Thao trường thiết kế và vận hành doanh nghiệp toàn diện",
    shortTitle: "BMDO",
    group: "ceo",
    audience: "Nhà sáng lập, doanh chủ, CEO, thành viên ban lãnh đạo.",
    audienceList: ["Nhà sáng lập", "Doanh chủ", "CEO", "Thành viên ban lãnh đạo"],
    problem:
      "Lãnh đạo nhìn doanh nghiệp theo từng mảng rời, khó xác định điểm nghẽn ưu tiên và thiết kế các cấu phần quản trị đồng bộ.",
    objectives: [
      "Nhìn rõ toàn bộ doanh nghiệp trên một cấu trúc thống nhất.",
      "Thiết kế các cấu phần quản trị đồng bộ.",
      "Nhận diện điểm nghẽn và nâng cao năng lực vận hành, thích ứng, phát triển.",
    ],
    topics: [
      "Toàn cảnh doanh nghiệp theo BizCar",
      "Chẩn đoán 12 khối chức năng",
      "Thiết kế quản trị đồng bộ",
      "Kế hoạch hành động và đo lường",
      "Chuẩn thành công 3W",
    ],
    topicCategories: ["lanh-dao-quan-tri", "chien-luoc-mo-hinh", "to-chuc-van-hanh"],
    methodology: `${defaultMethod} Gắn với mô hình BizCar và chuẩn WOW–WELL–WIN.`,
    deliverables: ["Hồ sơ thiết kế doanh nghiệp", "Phương án cải tiến", "Kế hoạch hành động có thể triển khai"],
    outcomes: [
      "Từng bước hoàn thiện hồ sơ thiết kế doanh nghiệp.",
      "Có phương án cải tiến và kế hoạch hành động trên doanh nghiệp thật.",
    ],
    duration: "30 buổi đào tạo thực hành",
    featured: true,
    status: "published",
    relatedPrograms: ["mbm", "thao-truong-khoi-nghiep"],
    relatedModels: ["bizcar", "3w"],
    seoDescription:
      "BMDO là thao trường 30 buổi đào tạo thực hành giúp CEO thiết kế và vận hành doanh nghiệp toàn diện trên nền mô hình BizCar và chuẩn 3W.",
  },
  {
    id: "mbm",
    slug: "mbm",
    title: "MBM — Chương trình làm chủ mô hình The BizCar",
    shortTitle: "MBM",
    englishName: "Mastery of the BizCar Model",
    group: "ceo",
    audience: "CEO, chuyên gia tư vấn, giảng viên, nhà quản lý và người muốn nghiên cứu, ứng dụng chuyên sâu BizCar.",
    audienceList: ["CEO", "Chuyên gia tư vấn", "Giảng viên", "Nhà quản lý", "Người nghiên cứu ứng dụng BizCar"],
    problem:
      "Nhiều người đã tiếp xúc BizCar nhưng chưa đủ độ sâu để phân tích, thiết kế, phản biện và đồng hành cải tiến doanh nghiệp trên một cấu trúc thống nhất.",
    objectives: [
      "Nghiên cứu, thiết kế, đo lường và chuẩn hóa mô hình BizCar.",
      "Ứng dụng toàn diện mô hình vào phân tích và đồng hành doanh nghiệp.",
    ],
    topics: ["Cấu trúc 12 khối", "Thiết kế và đo lường", "Phản biện mô hình", "Đồng hành cải tiến doanh nghiệp"],
    topicCategories: ["lanh-dao-quan-tri", "chien-luoc-mo-hinh"],
    methodology: defaultMethod,
    deliverables: ["Năng lực phân tích và thiết kế trên BizCar", "Năng lực phản biện và đồng hành cải tiến"],
    outcomes: [
      "Phân tích, thiết kế, phản biện và đồng hành cải tiến doanh nghiệp trên một cấu trúc quản trị thống nhất.",
    ],
    duration: "12 tháng",
    certificate:
      "Chứng nhận chuyên môn MBM do VABIX cấp theo tiêu chuẩn của chương trình. Đây không phải bằng cấp học thuật hay chứng chỉ được nhà nước công nhận.",
    featured: true,
    status: "published",
    relatedPrograms: ["bmdo"],
    relatedModels: ["bizcar", "3w"],
    seoDescription:
      "MBM — Mastery of the BizCar Model: chương trình 12 tháng làm chủ mô hình BizCar cho CEO, chuyên gia tư vấn và giảng viên.",
  },
  {
    id: "thao-truong-khoi-nghiep",
    slug: "thao-truong-khoi-nghiep",
    title: "Thao trường dành cho chiến binh khởi nghiệp",
    shortTitle: "Thao trường khởi nghiệp",
    group: "ceo",
    audience: "Nhà sáng lập, doanh chủ, đội ngũ điều hành startup.",
    audienceList: ["Nhà sáng lập", "Doanh chủ", "Đội ngũ điều hành startup"],
    problem:
      "Startup dễ sa vào sản phẩm chưa được kiểm chứng khách hàng, mô hình doanh thu chưa rõ và thiếu bằng chứng kinh doanh.",
    objectives: [
      "Kiểm chứng khách hàng.",
      "Hoàn thiện giá trị cung cấp và mô hình doanh thu.",
      "Tổ chức thực thi và tạo bằng chứng kinh doanh.",
    ],
    topics: ["Khách hàng và giá trị cung cấp", "Mô hình doanh thu", "Tổ chức thực thi", "Bằng chứng kinh doanh"],
    topicCategories: ["chien-luoc-mo-hinh", "thi-truong-khach-hang"],
    methodology: defaultMethod,
    deliverables: ["Kế hoạch kinh doanh hoặc cải tiến cụ thể trên doanh nghiệp / dự án thật"],
    outcomes: ["Kế hoạch được xây dựng và triển khai trên doanh nghiệp hoặc dự án thật."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: true,
    status: "published",
    relatedPrograms: ["bmdo"],
    relatedModels: ["bizcar", "3w"],
    seoDescription:
      "Thao trường khởi nghiệp của VABIX giúp nhà sáng lập kiểm chứng khách hàng, hoàn thiện mô hình doanh thu và tạo bằng chứng kinh doanh.",
  },
  {
    id: "dam-phan-thuong-luong-lanh-dao",
    slug: "dam-phan-thuong-luong-lanh-dao",
    title: "Đàm phán và thương lượng dành cho lãnh đạo",
    shortTitle: "Đàm phán cho lãnh đạo",
    group: "ceo",
    audience: "Doanh chủ, CEO và thành viên ban lãnh đạo.",
    audienceList: ["Doanh chủ", "CEO", "Ban lãnh đạo"],
    problem: "Đàm phán thiếu chuẩn bị, dễ mất kiểm soát tiến trình và thỏa thuận không gắn với quan hệ dài hạn.",
    objectives: ["Chuẩn bị, dẫn dắt và kiểm soát đàm phán", "Tạo thỏa thuận có giá trị", "Duy trì quan hệ hợp tác"],
    topics: ["Chuẩn bị đàm phán", "Dẫn dắt tiến trình", "Kiểm soát", "Thỏa thuận có giá trị", "Quan hệ hợp tác"],
    topicCategories: ["lanh-dao-quan-tri", "thi-truong-khach-hang"],
    methodology: defaultMethod,
    deliverables: ["Khung chuẩn bị đàm phán", "Kế hoạch thương lượng trên tình huống thật"],
    outcomes: ["Lãnh đạo chủ động hơn trong đàm phán và giữ được quan hệ hợp tác."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["dam-phan-thuong-luong-cong-viec"],
    relatedModels: [],
    seoDescription: "Chương trình đàm phán và thương lượng dành cho lãnh đạo: chuẩn bị, dẫn dắt, kiểm soát và tạo thỏa thuận có giá trị.",
  },
  {
    id: "lanh-dao-tinh-thuc",
    slug: "lanh-dao-tinh-thuc",
    title: "Lãnh đạo tỉnh thức và kiến tạo",
    shortTitle: "Lãnh đạo tỉnh thức",
    group: "ceo",
    audience: "Doanh chủ, CEO và người dẫn dắt đội ngũ.",
    audienceList: ["Doanh chủ", "CEO", "Người dẫn dắt đội ngũ"],
    problem: "Quyết định bị chi phối bởi trạng thái, thiếu tự nhận thức và khó kiến tạo thay đổi tích cực.",
    objectives: ["Tự nhận thức", "Làm chủ trạng thái", "Nâng cao chất lượng quyết định", "Kiến tạo thay đổi tích cực"],
    topics: ["Tự nhận thức", "Làm chủ trạng thái", "Chất lượng quyết định", "Kiến tạo thay đổi"],
    topicCategories: ["lanh-dao-quan-tri", "con-nguoi-van-hoa"],
    methodology: defaultMethod,
    deliverables: ["Nhật ký tự nhận thức", "Cam kết thay đổi hành vi lãnh đạo"],
    outcomes: ["Lãnh đạo tỉnh thức hơn trong quyết định và cách kiến tạo môi trường."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["moi-truong-lam-viec-tich-cuc"],
    relatedModels: [],
    seoDescription: "Lãnh đạo tỉnh thức và kiến tạo: tự nhận thức, làm chủ trạng thái và nâng chất lượng quyết định.",
  },
  {
    id: "moi-truong-lam-viec-tich-cuc",
    slug: "moi-truong-lam-viec-tich-cuc",
    title: "Kiến tạo môi trường làm việc tích cực và hạnh phúc",
    shortTitle: "Môi trường làm việc tích cực",
    group: "ceo",
    audience: "Lãnh đạo và quản lý chịu trách nhiệm văn hóa, gắn kết và động lực đội ngũ.",
    audienceList: ["Lãnh đạo", "Quản lý", "Phụ trách văn hóa tổ chức"],
    problem: "Môi trường thiếu năng lượng, tin cậy và hợp tác làm giảm động lực và chất lượng thực thi.",
    objectives: ["Xây môi trường giàu năng lượng, tin cậy, hợp tác và tạo động lực"],
    topics: ["Năng lượng tập thể", "Tin cậy", "Hợp tác", "Động lực"],
    topicCategories: ["con-nguoi-van-hoa", "lanh-dao-quan-tri"],
    methodology: defaultMethod,
    deliverables: ["Nguyên tắc môi trường làm việc", "Kế hoạch can thiệp văn hóa"],
    outcomes: ["Tổ chức có hướng dẫn cụ thể để kiến tạo môi trường tích cực hơn."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["lanh-dao-tinh-thuc"],
    relatedModels: [],
    seoDescription: "Chương trình kiến tạo môi trường làm việc tích cực, tin cậy và tạo động lực cho doanh nghiệp.",
  },
  {
    id: "phat-hien-phat-trien-nhan-tai",
    slug: "phat-hien-phat-trien-nhan-tai",
    title: "Phát hiện, phát triển và giữ chân nhân tài",
    shortTitle: "Phát triển nhân tài",
    group: "ceo",
    audience: "Doanh chủ, CEO, giám đốc nhân sự và quản lý phụ trách kế thừa.",
    audienceList: ["Doanh chủ", "CEO", "Giám đốc nhân sự", "Quản lý phụ trách kế thừa"],
    problem: "Doanh nghiệp phụ thuộc cá nhân then chốt, thiếu đội ngũ kế thừa và cơ chế giữ chân người phù hợp.",
    objectives: ["Nhận diện tiềm năng", "Tạo điều kiện phát triển", "Xây đội ngũ kế thừa", "Giữ chân nhân sự phù hợp"],
    topics: ["Nhận diện tiềm năng", "Điều kiện phát triển", "Đội ngũ kế thừa", "Giữ chân nhân sự"],
    topicCategories: ["con-nguoi-van-hoa", "lanh-dao-quan-tri"],
    methodology: defaultMethod,
    deliverables: ["Khung nhận diện tiềm năng", "Hướng phát triển kế thừa"],
    outcomes: ["Lãnh đạo có cách nhìn hệ thống hơn về nhân tài và kế thừa."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["quan-tri-nhan-su-quan-ly"],
    relatedModels: ["klass"],
    seoDescription: "Phát hiện, phát triển và giữ chân nhân tài: nhận diện tiềm năng, kế thừa và giữ chân nhân sự phù hợp.",
  },
  {
    id: "nang-luc-so-ai-lanh-dao",
    slug: "nang-luc-so-ai-lanh-dao",
    title: "Năng lực số và ứng dụng AI dành cho lãnh đạo",
    shortTitle: "AI dành cho lãnh đạo",
    group: "ceo",
    audience: "CEO, ban lãnh đạo và quản lý cần dẫn dắt ứng dụng công nghệ / AI.",
    audienceList: ["CEO", "Ban lãnh đạo", "Quản lý"],
    problem: "Lãnh đạo hoặc quá kỳ vọng, hoặc e ngại AI — thiếu cách chọn use case và dẫn dắt triển khai có trách nhiệm.",
    objectives: ["Hiểu đúng công nghệ / AI", "Chọn use case", "Dẫn dắt triển khai"],
    topics: ["Nhận thức AI cho lãnh đạo", "Chọn use case", "Dẫn dắt triển khai", "Rủi ro dữ liệu và trách nhiệm"],
    topicCategories: ["cong-nghe-ai", "lanh-dao-quan-tri"],
    methodology: defaultMethod,
    deliverables: ["Danh mục use case ưu tiên", "Nguyên tắc dẫn dắt triển khai AI"],
    outcomes: ["Lãnh đạo có cách chọn và dẫn dắt AI phù hợp bối cảnh doanh nghiệp."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: true,
    status: "published",
    relatedPrograms: ["ung-dung-ai-hieu-suat"],
    relatedModels: [],
    seoDescription: "Năng lực số và ứng dụng AI dành cho lãnh đạo: hiểu đúng công nghệ, chọn use case và dẫn dắt triển khai.",
  },
  {
    id: "quan-tri-tai-chinh-lanh-dao",
    slug: "quan-tri-tai-chinh-lanh-dao",
    title: "Quản trị tài chính dành cho lãnh đạo không chuyên tài chính",
    shortTitle: "Tài chính cho lãnh đạo",
    group: "ceo",
    audience: "Doanh chủ, CEO và lãnh đạo không xuất thân từ tài chính.",
    audienceList: ["Doanh chủ", "CEO", "Lãnh đạo không chuyên tài chính"],
    problem: "Lãnh đạo khó đọc sức khỏe tài chính, dòng tiền và chi phí nên quyết định thiếu dữ liệu.",
    objectives: ["Đọc hiểu sức khỏe tài chính", "Hiểu lợi nhuận, dòng tiền, chi phí", "Dùng dữ liệu tài chính để quyết định"],
    topics: ["Sức khỏe tài chính", "Lợi nhuận", "Dòng tiền", "Chi phí", "Dữ liệu để quyết định"],
    topicCategories: ["tai-chinh", "lanh-dao-quan-tri"],
    methodology: defaultMethod,
    deliverables: ["Khung đọc báo cáo cho lãnh đạo", "Câu hỏi tài chính then chốt khi ra quyết định"],
    outcomes: ["Lãnh đạo tự tin hơn khi đọc số liệu và đặt câu hỏi tài chính đúng."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["tai-chinh-ke-toan-quan-ly"],
    relatedModels: ["bizcar"],
    seoDescription: "Quản trị tài chính dành cho lãnh đạo không chuyên: đọc sức khỏe tài chính, lợi nhuận, dòng tiền và chi phí.",
  },
  {
    id: "ban-hang-thuc-chien",
    slug: "ban-hang-thuc-chien",
    title: "Bán hàng thực chiến trong thời đại số",
    shortTitle: "Bán hàng thực chiến",
    group: "management",
    audience: "Đội ngũ bán hàng, phát triển thị trường và quản lý sales.",
    audienceList: ["Nhân viên bán hàng", "Quản lý sales", "Phát triển thị trường"],
    problem: "Đội ngũ tìm khách hàng manh mún, tư vấn chưa rõ giá trị, khó xử lý phản đối và chốt bán.",
    objectives: ["Tìm kiếm khách hàng", "Tư vấn giá trị", "Xử lý phản đối", "Chốt bán", "Xây dựng quan hệ"],
    topics: ["Tìm khách hàng", "Tư vấn giá trị", "Xử lý phản đối", "Chốt bán", "Quan hệ khách hàng"],
    topicCategories: ["thi-truong-khach-hang"],
    methodology: defaultMethod,
    deliverables: ["Kịch bản tư vấn giá trị", "Kế hoạch chăm sóc sau bán"],
    outcomes: ["Đội ngũ bán hàng có quy trình thực chiến rõ hơn trên khách hàng thật."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: true,
    status: "published",
    relatedPrograms: ["cham-soc-khach-hang", "truyen-thong-doanh-nghiep"],
    relatedModels: ["baboso", "b2a"],
    seoDescription: "Bán hàng thực chiến trong thời đại số: tìm khách hàng, tư vấn giá trị, xử lý phản đối, chốt bán và xây quan hệ.",
  },
  {
    id: "truyen-thong-doanh-nghiep",
    slug: "truyen-thong-doanh-nghiep",
    title: "Truyền thông doanh nghiệp trong thời đại số",
    shortTitle: "Truyền thông doanh nghiệp",
    group: "management",
    audience: "Người phụ trách truyền thông, marketing và lãnh đạo cần thông điệp nhất quán.",
    audienceList: ["Truyền thông", "Marketing", "Lãnh đạo"],
    problem: "Thông điệp phân tán, kênh rời rạc, hình ảnh không nhất quán làm giảm niềm tin thị trường.",
    objectives: ["Làm rõ thông điệp", "Chọn kênh", "Phối hợp truyền thông", "Giữ hình ảnh nhất quán"],
    topics: ["Thông điệp", "Kênh", "Phối hợp truyền thông", "Hình ảnh nhất quán"],
    topicCategories: ["thi-truong-khach-hang"],
    methodology: defaultMethod,
    deliverables: ["Khung thông điệp", "Nguyên tắc phối hợp kênh"],
    outcomes: ["Doanh nghiệp có ngôn ngữ truyền thông thống nhất hơn."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["ban-hang-thuc-chien"],
    relatedModels: ["baboso"],
    seoDescription: "Truyền thông doanh nghiệp trong thời đại số: thông điệp, kênh, phối hợp và hình ảnh nhất quán.",
  },
  {
    id: "quan-tri-nhan-su-quan-ly",
    slug: "quan-tri-nhan-su-quan-ly",
    title: "Quản trị nhân sự dành cho nhà quản lý",
    shortTitle: "Nhân sự cho nhà quản lý",
    group: "management",
    audience: "Trưởng phòng, quản lý cấp trung và giám đốc chức năng.",
    audienceList: ["Trưởng phòng", "Quản lý cấp trung", "Giám đốc chức năng"],
    problem: "Quản lý tuyển, giao việc, đánh giá và phát triển nhân sự theo cảm tính, thiếu hệ thống.",
    objectives: ["Tuyển chọn", "Giao việc", "Đánh giá", "Phản hồi", "Phát triển và giữ chân"],
    topics: ["Tuyển chọn", "Giao việc", "Đánh giá", "Phản hồi", "Phát triển", "Giữ chân"],
    topicCategories: ["con-nguoi-van-hoa", "to-chuc-van-hanh"],
    methodology: defaultMethod,
    deliverables: ["Khung giao việc và đánh giá", "Thói quen phản hồi"],
    outcomes: ["Nhà quản lý quản nhân sự trong phạm vi đội ngũ có hệ thống hơn."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["phat-hien-phat-trien-nhan-tai", "quan-ly-cong-viec-hieu-suat"],
    relatedModels: ["klass"],
    seoDescription: "Quản trị nhân sự dành cho nhà quản lý: tuyển chọn, giao việc, đánh giá, phản hồi, phát triển và giữ chân.",
  },
  {
    id: "quan-ly-cong-viec-hieu-suat",
    slug: "quan-ly-cong-viec-hieu-suat",
    title: "Quản lý công việc và nâng cao hiệu suất",
    shortTitle: "Quản lý công việc",
    group: "management",
    audience: "Quản lý, trưởng nhóm và nhân sự cần hoàn thành đúng yêu cầu.",
    audienceList: ["Quản lý", "Trưởng nhóm", "Nhân sự thực thi"],
    problem: "Ưu tiên rối, thiếu kế hoạch, phối hợp yếu và khó theo dõi tiến độ.",
    objectives: ["Ưu tiên", "Lập kế hoạch", "Phối hợp", "Theo dõi tiến độ", "Hoàn thành đúng yêu cầu"],
    topics: ["Ưu tiên", "Lập kế hoạch", "Phối hợp", "Theo dõi tiến độ", "Hoàn thành"],
    topicCategories: ["to-chuc-van-hanh"],
    methodology: defaultMethod,
    deliverables: ["Khung ưu tiên công việc", "Cách theo dõi tiến độ"],
    outcomes: ["Công việc được ưu tiên và hoàn thành đúng yêu cầu rõ hơn."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["quan-tri-nhan-su-quan-ly"],
    relatedModels: [],
    seoDescription: "Quản lý công việc và nâng cao hiệu suất: ưu tiên, lập kế hoạch, phối hợp và theo dõi tiến độ.",
  },
  {
    id: "dam-phan-thuong-luong-cong-viec",
    slug: "dam-phan-thuong-luong-cong-viec",
    title: "Đàm phán và thương lượng trong công việc",
    shortTitle: "Đàm phán trong công việc",
    group: "management",
    audience: "Quản lý, nhân sự dự án, sales và người thường xuyên thỏa thuận nội bộ hoặc với đối tác.",
    audienceList: ["Quản lý", "Nhân sự dự án", "Sales"],
    problem: "Thiếu chuẩn bị khi thương lượng nội bộ hoặc với đối tác, dễ kéo dài xung đột.",
    objectives: ["Chuẩn bị", "Giao tiếp", "Xử lý khác biệt", "Xây dựng thỏa thuận nội bộ / đối tác"],
    topics: ["Chuẩn bị", "Giao tiếp", "Xử lý khác biệt", "Thỏa thuận"],
    topicCategories: ["lanh-dao-quan-tri", "thi-truong-khach-hang"],
    methodology: defaultMethod,
    deliverables: ["Mẫu chuẩn bị thương lượng", "Khung xử lý khác biệt"],
    outcomes: ["Người học thương lượng có chuẩn bị hơn trong công việc hàng ngày."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["dam-phan-thuong-luong-lanh-dao"],
    relatedModels: [],
    seoDescription: "Đàm phán và thương lượng trong công việc: chuẩn bị, giao tiếp, xử lý khác biệt và xây thỏa thuận.",
  },
  {
    id: "tai-chinh-ke-toan-quan-ly",
    slug: "tai-chinh-ke-toan-quan-ly",
    title: "Tài chính và kế toán dành cho nhà quản lý không chuyên",
    shortTitle: "Tài chính cho nhà quản lý",
    group: "management",
    audience: "Quản lý phòng ban không chuyên tài chính.",
    audienceList: ["Quản lý phòng ban", "Trưởng nhóm"],
    problem: "Quản lý không đọc được ngân sách, chi phí, doanh thu trong phạm vi mình chịu trách nhiệm.",
    objectives: ["Hiểu thông tin tài chính", "Ngân sách, chi phí, doanh thu", "Trách nhiệm tài chính trong phạm vi công việc"],
    topics: ["Thông tin tài chính", "Ngân sách", "Chi phí", "Doanh thu", "Trách nhiệm tài chính"],
    topicCategories: ["tai-chinh", "to-chuc-van-hanh"],
    methodology: defaultMethod,
    deliverables: ["Khung đọc số liệu phòng ban", "Câu hỏi trách nhiệm tài chính"],
    outcomes: ["Nhà quản lý hiểu phạm vi trách nhiệm tài chính của mình rõ hơn."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["quan-tri-tai-chinh-lanh-dao"],
    relatedModels: ["bizcar"],
    seoDescription: "Tài chính và kế toán dành cho nhà quản lý không chuyên: ngân sách, chi phí, doanh thu và trách nhiệm tài chính.",
  },
  {
    id: "cham-soc-khach-hang",
    slug: "cham-soc-khach-hang",
    title: "Chăm sóc khách hàng chuyên nghiệp",
    shortTitle: "Chăm sóc khách hàng",
    group: "management",
    audience: "Đội ngũ CSKH, sales và nhân sự tiếp xúc khách hàng.",
    audienceList: ["CSKH", "Sales", "Nhân sự tiếp xúc khách hàng"],
    problem: "Thiếu thấu hiểu khách hàng, phản hồi chậm, xử lý khiếu nại chưa tạo trải nghiệm tích cực.",
    objectives: ["Thấu hiểu khách hàng", "Giao tiếp", "Phản hồi", "Xử lý khiếu nại", "Trải nghiệm tích cực"],
    topics: ["Thấu hiểu khách hàng", "Giao tiếp", "Phản hồi", "Khiếu nại", "Trải nghiệm"],
    topicCategories: ["thi-truong-khach-hang"],
    methodology: defaultMethod,
    deliverables: ["Khung xử lý khiếu nại", "Nguyên tắc trải nghiệm khách hàng"],
    outcomes: ["Đội ngũ chăm sóc khách hàng có cách làm việc chuyên nghiệp và nhất quán hơn."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: false,
    status: "published",
    relatedPrograms: ["ban-hang-thuc-chien"],
    relatedModels: ["baboso"],
    seoDescription: "Chăm sóc khách hàng chuyên nghiệp: thấu hiểu, giao tiếp, phản hồi, xử lý khiếu nại và trải nghiệm tích cực.",
  },
  {
    id: "ung-dung-ai-hieu-suat",
    slug: "ung-dung-ai-hieu-suat",
    title: "Ứng dụng AI để nâng cao hiệu suất công việc",
    shortTitle: "AI nâng cao hiệu suất",
    group: "management",
    audience: "Nhân viên văn phòng, quản lý và phòng ban cần giảm thao tác lặp lại.",
    audienceList: ["Nhân viên văn phòng", "Quản lý", "Phòng ban"],
    problem: "AI được dùng rời rạc, chưa gắn nhiệm vụ phù hợp nên ít cải thiện tốc độ và chất lượng.",
    objectives: ["Ứng dụng AI vào nhiệm vụ phù hợp", "Giảm thao tác lặp lại", "Tăng tốc độ và chất lượng"],
    topics: ["Chọn nhiệm vụ phù hợp", "Thao tác lặp lại", "Chất lượng đầu ra", "Sử dụng AI có trách nhiệm"],
    topicCategories: ["cong-nghe-ai"],
    methodology: defaultMethod,
    deliverables: ["Use case cá nhân / nhóm", "Quy ước sử dụng AI trong công việc"],
    outcomes: ["Người học gắn AI vào nhiệm vụ phù hợp thay vì dùng tùy hứng."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: true,
    status: "published",
    relatedPrograms: ["nang-luc-so-ai-lanh-dao"],
    relatedModels: [],
    seoDescription: "Ứng dụng AI để nâng cao hiệu suất công việc: chọn nhiệm vụ phù hợp, giảm thao tác lặp lại, tăng chất lượng.",
  },
  {
    id: "dao-tao-theo-yeu-cau",
    slug: "dao-tao-theo-yeu-cau",
    title: "Đào tạo theo yêu cầu doanh nghiệp",
    shortTitle: "Đào tạo theo yêu cầu",
    group: "custom",
    audience: "Ban lãnh đạo, quản lý, phòng ban và nhân sự theo mục tiêu chung của doanh nghiệp.",
    audienceList: ["Ban lãnh đạo", "Quản lý", "Phòng ban", "Nhân sự theo mục tiêu chung"],
    problem: "Chương trình sẵn có không khớp ngành nghề, đối tượng, mục tiêu và điều kiện thực tế của doanh nghiệp.",
    objectives: [
      "Thiết kế riêng sau khảo sát hiện trạng, mục tiêu, vấn đề, ngành nghề và điều kiện thực tế.",
    ],
    topics: ["Tùy chỉnh theo khảo sát", "Có thể kết hợp các chuyên đề trong danh mục VABIX"],
    topicCategories: [
      "lanh-dao-quan-tri",
      "chien-luoc-mo-hinh",
      "to-chuc-van-hanh",
      "con-nguoi-van-hoa",
      "thi-truong-khach-hang",
      "tai-chinh",
      "cong-nghe-ai",
    ],
    methodology: "Khảo sát mục tiêu, đối tượng, hiện trạng và kết quả mong đợi trước khi đề xuất nội dung, thời lượng, phương pháp và đội ngũ chuyên gia.",
    deliverables: ["Đề xuất chương trình sau khảo sát", "Học liệu và sản phẩm thực hành theo thỏa thuận"],
    outcomes: ["Nhận thức chung, thực hành trên công việc, sản phẩm hoặc kế hoạch cải tiến."],
    durationNote: "Thời lượng được thiết kế theo nhu cầu",
    featured: true,
    status: "published",
    relatedPrograms: ["bmdo"],
    relatedModels: ["bizcar", "3w"],
    seoDescription: "Đào tạo theo yêu cầu doanh nghiệp: thiết kế sau khảo sát hiện trạng, mục tiêu, ngành nghề và điều kiện thực tế.",
  },
];

export const programGroups: { id: TrainingProgram["group"]; label: string }[] = [
  { id: "ceo", label: "Dành cho doanh chủ & CEO" },
  { id: "management", label: "Dành cho đội ngũ quản lý & nhân viên" },
  { id: "custom", label: "Đào tạo theo yêu cầu doanh nghiệp" },
];

export function getProgram(slug: string) {
  return programs.find((p) => p.slug === slug && p.status === "published");
}

export function featuredPrograms() {
  return programs.filter((p) => p.featured && p.status === "published");
}
