import type { Redirect } from "next/dist/lib/load-custom-routes";

/**
 * Preserve important ShopXanh / vabix.vn URLs by mapping them
 * into the new information architecture.
 */
export const legacyRedirects: Redirect[] = [
  { source: "/tin-tuc-trong-ngay", destination: "/tri-thuc", permanent: true },
  { source: "/tin-tuc-trong-ngay.html", destination: "/tri-thuc", permanent: true },
  { source: "/gioi-thieu-vabix", destination: "/ve-vabix", permanent: true },
  { source: "/gioi-thieu-vabix.html", destination: "/ve-vabix", permanent: true },
  { source: "/doi-net-tu-gioi-thieu-ve-lang-vabix_bm.html", destination: "/ve-vabix", permanent: true },
  { source: "/su-menhkhat-vong", destination: "/ve-vabix", permanent: true },
  { source: "/su-menh-khat-vong", destination: "/ve-vabix", permanent: true },
  { source: "/gia-tri-cot-loi", destination: "/ve-vabix", permanent: true },
  { source: "/sau-chu-vang-cua-lang_bm.html", destination: "/ve-vabix", permanent: true },
  { source: "/mang-luoi-vabix", destination: "/mang-luoi", permanent: true },
  { source: "/cac-thuat-ngu-cua-lang-vabix", destination: "/ve-vabix", permanent: true },
  { source: "/cu-dan-hoc-tap", destination: "/cong-cu-dan", permanent: true },
  { source: "/cu-dan-ket-noi", destination: "/cong-cu-dan", permanent: true },
  { source: "/login-page", destination: "/cong-cu-dan", permanent: true },
  { source: "/login-page.html", destination: "/cong-cu-dan", permanent: true },
  { source: "/career-group", destination: "/mang-luoi/lang-nganh", permanent: true },
  { source: "/career-web-group", destination: "/mang-luoi/nha-cung-cap", permanent: true },
  { source: "/nha-cung-cap", destination: "/mang-luoi/tro-thanh-doi-tac", permanent: true },
  { source: "/khach-tham-quan", destination: "/mang-luoi/nha-cung-cap", permanent: true },
  { source: "/su-kien-ket-noi", destination: "/su-kien", permanent: true },
  { source: "/san-pham-vabix", destination: "/tri-thuc/sach", permanent: true },
  { source: "/contact-page.html", destination: "/lien-he", permanent: true },
  { source: "/chinh-sach-quyen-rieng-tu_bm.html", destination: "/chinh-sach-quyen-rieng-tu", permanent: true },
  { source: "/bao-mat-thong-tin", destination: "/chinh-sach-bao-mat", permanent: true },
  { source: "/khuyen-cao-gia-tri", destination: "/khuyen-cao", permanent: true },
  { source: "/ho-so-nang-luc-vabix", destination: "/ve-vabix", permanent: true },
  { source: "/ho-so-nang-luc", destination: "/mang-luoi/tro-thanh-doi-tac", permanent: true },
  { source: "/brochure-san-pham-dich-vu", destination: "/ve-vabix", permanent: true },
  { source: "/quan-ly-tai-chinh-ca-nhan", destination: "/tri-thuc/cam-nang/quan-ly-tai-chinh-ca-nhan", permanent: true },
  { source: "/lua-chon-thiet-bi-truyen-thong", destination: "/tri-thuc/cam-nang/lua-chon-thiet-bi-truyen-thong", permanent: true },
  { source: "/cam-nang-ve-gao", destination: "/tri-thuc/cam-nang/cam-nang-ve-gao", permanent: true },
  { source: "/cam-nang-ve-gach", destination: "/tri-thuc/cam-nang/cam-nang-ve-gach", permanent: true },
  { source: "/lua-chon-noi-that", destination: "/tri-thuc/cam-nang/lua-chon-noi-that", permanent: true },
  { source: "/mua-san-pham-sach", destination: "/tri-thuc/cam-nang/mua-san-pham-sach", permanent: true },
  { source: "/cam-nang-du-lich", destination: "/tri-thuc/cam-nang/cam-nang-du-lich", permanent: true },
  { source: "/quyet-dinh-bo-nhiem", destination: "/bo-suu-tap/quyet-dinh-bo-nhiem", permanent: true },
  { source: "/hinh-anh-ky-ket", destination: "/bo-suu-tap/hinh-anh-ky-ket", permanent: true },
  { source: "/hinh-anh-dao-tao", destination: "/bo-suu-tap/hinh-anh-dao-tao", permanent: true },
  { source: "/hinh-anh-hoat-dong", destination: "/bo-suu-tap/hinh-anh-ket-noi", permanent: true },
  { source: "/bo-chung-nhan", destination: "/bo-suu-tap/mau-chung-nhan", permanent: true },
  { source: "/ho-tro-doanh-nhan-viet-sach", destination: "/dich-vu-phu-tro/ho-tro-doanh-nhan-viet-sach", permanent: true },
  { source: "/co-van-dong-hanh-thuc-chien", destination: "/giai-phap/tu-van-chien-luoc", permanent: true },
  { source: "/dich-vu-cho-thue-nhan-luc", destination: "/dich-vu-phu-tro/nhan-luc-thoi-vu", permanent: true },
  { source: "/dich-vu-nguoi-dien-thuyet", destination: "/dich-vu-phu-tro/nha-dien-thuyet", permanent: true },
  { source: "/dich-vu-kol", destination: "/dich-vu-phu-tro/ket-noi-kol", permanent: true },
  { source: "/workshop-chua-lanh-va-nang-luong-danh-cho-ceo_bm.html", destination: "/su-kien/workshop-chua-lanh-nang-luong-ceo-bmdo-01", permanent: true },
  { source: "/le-ky-ket-hop-tac_bm.html", destination: "/su-kien/le-ra-mat-nen-tang-vabix", permanent: true },
  { source: "/bai-viet-demo-3_bm.html", destination: "/su-kien/dao-tao-cu-dan-ket-noi", permanent: true },
  { source: "/bai-viet-demo-2_bm.html", destination: "/su-kien/ket-noi-khach-hang-chung-cu", permanent: true },
];
