export const topicCategories = [
  { id: "lanh-dao-quan-tri", label: "Lãnh đạo & quản trị" },
  { id: "chien-luoc-mo-hinh", label: "Chiến lược & mô hình kinh doanh" },
  { id: "to-chuc-van-hanh", label: "Tổ chức & vận hành" },
  { id: "con-nguoi-van-hoa", label: "Con người & văn hóa" },
  { id: "thi-truong-khach-hang", label: "Thị trường & khách hàng" },
  { id: "tai-chinh", label: "Tài chính doanh nghiệp" },
  { id: "cong-nghe-ai", label: "Công nghệ số & AI" },
] as const;

export const trainingGroups = [
  {
    id: "ceo",
    number: "01",
    title: "Đào tạo và huấn luyện CEO",
    audience:
      "Nhà sáng lập, doanh chủ, Tổng Giám đốc, Giám đốc điều hành, thành viên ban lãnh đạo, người có quyền quyết định.",
    goal: "Nhìn toàn diện doanh nghiệp, xác định đúng vấn đề, thiết kế quản trị đồng bộ và nâng cao năng lực điều hành.",
    topics: [
      "Định hướng",
      "Khách hàng / thị trường",
      "Mô hình kinh doanh",
      "Nhân lực",
      "Tài chính",
      "Tổ chức",
      "Thương hiệu",
      "Văn hóa",
      "Nguồn lực tăng trưởng",
      "Lãnh đạo",
      "Công nghệ số / AI",
    ],
    outcomes: ["Bản đánh giá", "Điểm nghẽn ưu tiên", "Thiết kế quản trị", "Kế hoạch cải tiến", "Cơ chế đo lường"],
  },
  {
    id: "custom",
    number: "02",
    title: "Đào tạo theo yêu cầu doanh nghiệp",
    audience: "Ban lãnh đạo, quản lý, phòng ban, nhân sự theo mục tiêu chung.",
    goal: "Thiết kế dựa trên hiện trạng, mục tiêu, vấn đề, ngành nghề và điều kiện thực tế của từng tổ chức.",
    topics: ["Chiến lược", "Sales", "Khách hàng", "Quản lý", "Quy trình", "Văn hóa", "KPI", "Công nghệ / AI", "Nội dung tùy chỉnh"],
    outcomes: ["Nhận thức chung", "Thực hành trên công việc", "Sản phẩm hoặc kế hoạch cải tiến"],
  },
  {
    id: "managers",
    number: "03",
    title: "Phát triển đội ngũ quản lý",
    audience: "Giám đốc chức năng, trưởng/phó phòng, quản lý cấp trung, trưởng nhóm và nhân sự kế thừa.",
    goal: "Làm rõ trách nhiệm, giao việc và đánh giá có hệ thống, giảm phụ thuộc quá mức vào CEO.",
    topics: [
      "Vai trò / điều hành",
      "Phân quyền",
      "Giao việc",
      "Lập kế hoạch",
      "Hiệu suất",
      "Phản hồi",
      "Giải quyết vấn đề",
      "Phối hợp liên phòng ban",
      "Xung đột",
      "Thay đổi",
      "Phát triển kế thừa",
    ],
    outcomes: ["Trách nhiệm rõ", "Giao việc / đánh giá có hệ thống", "Giảm phụ thuộc quá mức vào CEO"],
  },
  {
    id: "staff",
    number: "04",
    title: "Phát triển năng lực đội ngũ",
    audience: "Nhân viên, sales, chăm sóc khách hàng, nhân sự dự án và các đội ngũ cần cải thiện thực thi.",
    goal: "Giảm sai sót, chờ đợi, làm lại; tăng năng suất và chất lượng công việc.",
    topics: [
      "Trách nhiệm",
      "Chủ động",
      "Thời gian",
      "Giao tiếp",
      "Teamwork",
      "Giải quyết vấn đề",
      "Cải tiến",
      "Bán hàng",
      "Trải nghiệm khách hàng",
      "Dữ liệu",
      "AI",
    ],
    outcomes: ["Giảm sai sót / chờ đợi / làm lại", "Tăng năng suất", "Nâng chất lượng công việc"],
  },
  {
    id: "ai",
    number: "05",
    title: "Đào tạo ứng dụng AI trong doanh nghiệp",
    audience: "CEO, lãnh đạo, quản lý, nhân viên văn phòng và phòng ban.",
    goal: "Xác định use case phù hợp, thiết kế quy trình human–AI và sử dụng AI có trách nhiệm — không hứa tỷ lệ tiết kiệm khi chưa đo lường.",
    topics: [
      "Nhận thức nền tảng về AI",
      "Xác định công việc phù hợp để ứng dụng AI",
      "AI trong quản trị và ra quyết định",
      "AI trong bán hàng và marketing",
      "AI trong nhân sự, tài chính và vận hành",
      "Thiết kế quy trình làm việc có AI hỗ trợ",
      "Phối hợp nhân lực thật và nhân lực số",
      "Xây dựng và sử dụng AI Agent",
      "Bảo mật dữ liệu và sử dụng AI có trách nhiệm",
      "Đo lường hiệu quả ứng dụng AI",
    ],
    outcomes: ["Use case ưu tiên", "Quy trình human–AI", "Giảm thao tác lặp lại", "Nâng cao năng suất và chất lượng"],
  },
  {
    id: "coaching",
    number: "06",
    title: "Huấn luyện CEO 1:1",
    audience: "Doanh chủ và CEO cần làm rõ vấn đề, quyết định và kế hoạch trên bài toán thật của doanh nghiệp.",
    goal: "Mỗi phiên tập trung vào một vấn đề hoặc quyết định thực tế, đi từ làm rõ đến theo dõi hiệu chỉnh.",
    topics: [
      "Làm rõ vấn đề / mục tiêu",
      "Phân biệt dữ kiện / nhận định / giả định",
      "Xác định điểm nghẽn",
      "Phân tích phương án",
      "Chọn quyết định",
      "Lập kế hoạch",
      "Theo dõi và hiệu chỉnh",
    ],
    outcomes: ["Vấn đề được làm rõ", "Quyết định được lựa chọn", "Kế hoạch có người thực hiện, thời hạn và tiêu chí theo dõi"],
  },
];

export const trainingMethod = {
  steps: [
    { title: "Mô thức quản trị", body: "Khung tư duy và ngôn ngữ chung để nhìn doanh nghiệp." },
    { title: "Ví dụ thực tế", body: "Tình huống đã diễn ra trong bối cảnh doanh nghiệp Việt." },
    { title: "Thực hành trên doanh nghiệp", body: "Học viên làm trên dữ liệu và bài toán thật của mình." },
    { title: "Phản biện đa chiều", body: "Đối chiếu giả định, phương án và rủi ro trước khi chốt." },
    { title: "Cải tiến", body: "Điều chỉnh sản phẩm quản trị sau phản biện." },
    { title: "Cam kết ứng dụng", body: "Xác định người làm, thời hạn và cách theo dõi." },
  ],
  possibleOutputs: [
    "Bản đánh giá hiện trạng.",
    "Bản thiết kế quản trị.",
    "Quy trình hoặc phương án cải tiến.",
    "Kế hoạch hành động.",
    "Bộ chỉ số theo dõi.",
    "Báo cáo kết quả ứng dụng.",
  ],
  designProcess: [
    { step: "01", title: "Khảo sát", body: "Làm rõ mục tiêu, đối tượng, hiện trạng và kết quả mong đợi." },
    { step: "02", title: "Đề xuất", body: "Thiết kế nội dung, thời lượng, phương pháp và đội ngũ chuyên gia phù hợp." },
    { step: "03", title: "Triển khai", body: "Học – thực hành – phản biện trên bài toán thật." },
    { step: "04", title: "Theo dõi", body: "Cam kết ứng dụng và điều chỉnh sau chương trình." },
  ],
};
